version: '2'
services:
  web:
    container_name: adminPage
    build:
      context: .
      dockerfile: ./Dockerfile # Định nghĩa Dockerfile cho cả Nginx và PHP
    ports:
      - "8081:80"
    volumes:
      - ./src:/var/www/html
      - ./myapp.nginx.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www/html

  mysql:
    container_name: adminPage_db
    image: mysql:5.7.43
    command: 
      --default-authentication-plugin=mysql_native_password
      --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Gao@0105
      MYSQL_DATABASE: website_database
    ports:
      - "3309:3306"
    volumes:
      - ./src:/var/mydb/data
        
